### ISSUE TITLE
Training & inference time 

### ISSUE THREAD

**Issue by wzzheng** [tarashakhurana/4d-occ-forecasting#1]
Thanks for the exciting work! Could you let me know the approximate training and inference time? How much memory does it take for training and on what device? Thanks in advance!

**Comment by tarashakhurana** [comment]
Hi, thanks for your question! Training takes ~8hrs on nuScenes on 8 x NVIDIA RTX 3090s, while using up about 80% of its memory. Inference on the same GPU per batch happens at 3Hz.

**Comment by placeforyiming** [comment]
> Hi, thanks for your question! Training takes ~8hrs on nuScenes on 8 x NVIDIA RTX 3090s, while using up about 80% of its memory. Inference on the same GPU per batch happens at 3Hz.

According to the default settings, the test batch size is 2. Could you give some hinds about why the inference speed is slow?

**Comment by tarashakhurana** [comment]
Hi, the voxel grid size is too big for the network to process (700 x 700 x 45). If I remember correctly, this is what took the most amount of time during inference, and rendering (after the network's forward pass) is not the biggest bottleneck.
