### ISSUE TITLE
About the input occupancy

### ISSUE THREAD

**Issue by placeforyiming** [tarashakhurana/4d-occ-forecasting#12]
Hi, thanks for sharing the code

A quick question:

What is the exactly used method to transform the input point clouds to occupancy voxels as the network input?

From the implementation, if a voxel has at least one point inside of it, then the voxel is marked as 1. So no ray-casting is used here. However,  the comment here https://github.com/tarashakhurana/4d-occ-forecasting/blob/ff986082cd6ea10e67ab7839bf0e654736b3f4e2/model.py#L240 says the ray-casting is used and the space status is triple instead of binary.

**Comment by tarashakhurana** [comment]
Hi, thanks for the question! Unfortunately, the comment in the code is misleading and the input occupancy is binary. This is also explained in the paper in Section 3.

**Comment by placeforyiming** [comment]
> Hi, thanks for the question! Unfortunately, the comment in the code is misleading and the input occupancy is binary. This is also explained in the paper in Section 3.

Got it! Thanks for the quick reply
