### ISSUE TITLE
Can we extend when input resolution(voxel_size) is different in xyz dimensions?

### ISSUE THREAD

**Issue by synsin0** [tarashakhurana/4d-occ-forecasting#13]
I see both gt_dist and pred_dist are multiplied with voxel_size after, what if voxel size is different on xyz dimensions?

**Comment by tarashakhurana** [comment]
You can have different resolutions across all three axes! 

First of all, the cuda kernel is independent of the voxel resolutions. It only thinks of a grid as cells with integer-valued indices. 

Second, the multiplication of `gt_dist` with `voxel_size` of `0.2` is actually a multiplication with $\frac{\sqrt{0.2^2 + 0.2^2 + 0.2^2}}{\sqrt{1^2 + 1^2 +1^2}}$. You could instead have different resolutions with different axes and multiply `gt_dist` and `pred_dist` with $\frac{\sqrt{v_x^2 + v_y^2 + v_z^2}}{\sqrt{1^2 + 1^2 +1^2}}$. Let me know if you try this!
