### ISSUE TITLE
Evalai Leaderboard doesn't run the submission file.

### ISSUE THREAD

**Issue by foolhard** [tarashakhurana/4d-occ-forecasting#14]
Hello, 

I have submitted the test set result to Argoverse 2: 4D Occupancy Forecasting Challenge leaderboard last week. But the submission has not been evaluated yet and keep submitted status for  more than 3 days. 

Is there any issue on the evalai server? 

Regards

**Comment by tarashakhurana** [comment]
Hey, sorry for the late response (somehow I didn't get a notification for this issue).

On March 21, you exceeded the maximum number of entries allowed for a day. And on March 22, there was an OOM error on my end. I have reevaluated your March 22 submission, and the server should be running fine now if you have to submit any other results!

Thanks for your patience!

**Comment by foolhard** [comment]
Got it. Thanks for your response.

**Comment by mingyuShin** [comment]
@foolhard  @tarashakhurana 
Hello,

I am wondering if it is possible to submit to the Argoverse 2: 4D Occupancy Forecasting Challenge leaderboard. I am attempting to upload a JSON file (approximately 30GB) and it takes about 1.5 hours to upload. However, the connection URL expires after 1 hour, preventing me from completing the submission. Could you please confirm if the test set result is indeed around 30GB, and how long it typically takes for you to upload it?

Thank you.
