### ISSUE TITLE
2024 wad challenge submission.

### ISSUE THREAD

**Issue by mingyuShin** [tarashakhurana/4d-occ-forecasting#15]
Thank you for your great work!

I want to participate in the CVPR'24 4D occupancy forecasting challenge.

If I want to save the output of a pretrained 4D-OCC-forecasting baseline model in the format specified as /path/to/submission, what code should I use? If there isn't any, could you provide some reference code that I could refer to?

> Script to compute the metrics in the CVPR '23 paper and the leaderboard for the 4D occupancy forecasting challenge. Usage: python evaluate.py --annotations /path/to/annotations --submission /path/to/submission.

Another question, I can't acess the submission guidance url(https://eval.ai/web/challenges/challenge-page/1977/submission). Error message: Page Not Found 404.

**Comment by tarashakhurana** [comment]
Hey, thanks for your interest! I'm not sure why you are not able to view the link (I am able to access it). The submission file instructions are already there. Maybe you are not logged in the Eval AI portal? Can you try deleting cookies etc, or logging into Eval AI in an incognito window?

**Comment by mingyuShin** [comment]
Oh, thank you.

Now I can access the page.

I have another question. Is it possible to use the extrinsic parameter in order to train my own model? or is it cheating?
@tarashakhurana

**Comment by tarashakhurana** [comment]
you can use the extrinsics to train your model, as long as given a ray origin and direction at inference you can get the distance travelled by the ray from your model. This means that at inference, your model should not be dependent on an "extrinsics matrix".

**Comment by mingyuShin** [comment]
Thank you for your reply!
