### ISSUE TITLE
Visualization code issue

### ISSUE THREAD

**Issue by synsin0** [tarashakhurana/4d-occ-forecasting#17]
I'd like to ask how to write visualization code shown in the paper. How the 4D occupancy is visualized. Thankful if you may share the code or you give instructions on how to write the code.
![image](https://github.com/tarashakhurana/4d-occ-forecasting/assets/37300008/f6d2fcc5-73e9-4316-a4ed-1d6fa7c156dd)

**Comment by tarashakhurana** [comment]
Please see [this](https://github.com/tarashakhurana/4d-occ-forecasting/issues/6) issue.
