### ISSUE TITLE
Chamferdis module reported an error

### ISSUE THREAD

**Issue by Tkk0124** [tarashakhurana/4d-occ-forecasting#5]
Is there any exception in the provided chamferdis module version 1.0.0? The error is pointing to this module

The following is the error message
“Traceback (most recent call last):
  File "test.py", line 327, in <module>
    test(args)
  File "test.py", line 283, in test
    metrics["chamfer_distance"] += compute_chamfer_distance(pred_pcd, gt_pcd, device)
  File "/home/gdyanfa1/tmh/tmh_lidar_occ/4d-occ-forecasting-main/utils/evaluation.py", line 207, in compute_chamfer_distance
    cd_forward, cd_backward, CD_info = chamfer_distance(
  File "/home/gdyanfa1/miniconda3/envs/tmh_lidar_occ/lib/python3.8/site-packages/torch/_tensor.py", line 607, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor”

**Comment by flm8620** [comment]
You need to install the modified chamferdist package shipped from this repo, under utils/chamferdist.

You can use command like: `$ ~/4d-occ-forecasting/utils/chamferdist# pip install .`

**Comment by Tkk0124** [comment]
sure，It needs to be solved by linking other libraries in a ”pip insatll ." way

**Comment by Shuhul24** [comment]
Hey @Tkk0124 @flm8620 @tarashakhurana, I have installed python=3.8, CUDA=11.8, torch==2.0.0. I tried installing chamferdist==1.0.3 [instead of chamferdist==1.0.0 (installed via `pip install .` after navigating to `utils/chamferdist`)]. On doing so, I get the following error:
```python
/csehome/p24cs0005/4d-occ-forecasting/utils/evaluation.py:194: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at ../aten/src/ATen/native/IndexingUtils.h:27.)
  pred_pcd_inner = pred_pcd[inner_mask_pred]
/csehome/p24cs0005/4d-occ-forecasting/utils/evaluation.py:195: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at ../aten/src/ATen/native/IndexingUtils.h:27.)
  gt_pcd_inner = gt_pcd[inner_mask_gt]
Traceback (most recent call last):
  File "/csehome/p24cs0005/4d-occ-forecasting/test.py", line 317, in <module>
    test(args)
  File "/csehome/p24cs0005/4d-occ-forecasting/test.py", line 275, in test
    l1_error, absrel_error = compute_ray_errors(pred_pcd, gt_pcd, torch.from_numpy(origin), device)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/csehome/p24cs0005/4d-occ-forecasting/utils/evaluation.py", line 282, in compute_ray_errors
    _, info = chamfer_distance(
              ^^^^^^^^^^^^^^^^^
  File "/csehome/p24cs0005/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/csehome/p24cs0005/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ChamferDistance.forward() got an unexpected keyword argument 'reduction'
```

How to overcome this? I am getting somewhat different error after removing 'reduction' argument.

**Comment by yuhuanshih** [comment]
@Shuhul24 Hello, I encountered the same issue as you. Could you please let me know if you were able to resolve it? Thank you!

**Comment by Shuhul24** [comment]
Hey @yuhuanshih, this error arises because the version of chamferdist would have been 1.0.3 (which is not compatible with this repo). Hence you have got to install chamferdist as suggested in the repo. Let me know if you still facing the issue.

**Comment by yuhuanshih** [comment]
@Shuhul24 Thank you so much! I followed your method and succeeded!
