### ISSUE TITLE
CVPR Eval Kit Challenge Bug

### ISSUE THREAD

**Issue by BenAgro314** [tarashakhurana/4d-occ-forecasting#9]
Hello,

From what I understand about the challenge, the queries are meant to be at these 5 timesteps in the future:
```{0.6 s, 1.2 s, 1.8 s, 2.4 s, 3.0 s}```
However the current dataloader implemented in the CVPR eval kit loads queries at the following timesteps:
```{1.2 s, 2.4 s, 3.6 s, 4.8s , 6.0s}```,
which I think is incorrect. 

See `cvpr23-evalkit/data/av2.py` on line 72, where the stride is `self.input_step + self.output_step = 12`. This is implemented correctly in the other dataloader `data/av2.py` on line 78, where the stride is just `self.input_step`.

Thanks for any clarification and help.

**Comment by tarashakhurana** [comment]
Hey Ben, thanks for catching that! I fixed it now.
